<?php
declare(strict_types=1);

namespace Neos\OAuth\Infrastructure\League;

use Defuse\Crypto\Key;
use League\OAuth2\Server\CryptKey;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\Log\Utility\LogEnvironment;
use Neos\Utility\Files;
use Psr\Log\LoggerInterface;

/**
 * The RSA key pair that signs and verifies the access tokens, and the key that encrypts codes and refresh tokens
 *
 * They are either configured (Neos.OAuth.keys.privateKey etc., e.g. from environment variables), or kept in files that
 * are generated on first use
 */
#[Flow\Scope('singleton')]
final class KeyManager
{
    /**
     * @var array{privateKeyPath: string, publicKeyPath: string, encryptionKeyPath: string, privateKey: ?string, publicKey: ?string, encryptionKey: ?string}
     */
    #[Flow\InjectConfiguration(path: 'keys', package: 'Neos.OAuth')]
    protected array $settings;

    #[Flow\Inject]
    protected LoggerInterface $logger;

    public function getPrivateKey(): CryptKey
    {
        return new CryptKey($this->keyContents('privateKey'));
    }

    public function getPublicKey(): CryptKey
    {
        return new CryptKey($this->keyContents('publicKey'));
    }

    public function getEncryptionKey(): Key
    {
        return Key::loadFromAsciiSafeString(trim($this->keyContents('encryptionKey')));
    }

    /**
     * Whether the keys are configured rather than kept in files
     */
    public function keysAreConfigured(): bool
    {
        return ($this->settings['privateKey'] ?? null) !== null
            || ($this->settings['publicKey'] ?? null) !== null
            || ($this->settings['encryptionKey'] ?? null) !== null;
    }

    /**
     * @return array<string, bool> key file path => whether it exists
     */
    public function keyFiles(): array
    {
        $files = [];
        foreach (['privateKeyPath', 'publicKeyPath', 'encryptionKeyPath'] as $setting) {
            $files[$this->settings[$setting]] = is_file($this->settings[$setting]);
        }
        return $files;
    }

    public function keyFilesExist(): bool
    {
        return in_array(true, $this->keyFiles(), true);
    }

    /**
     * Creates a new RSA key pair and encryption key. Replacing existing ones invalidates all issued tokens and codes
     */
    public function generateKeys(): void
    {
        if ($this->keysAreConfigured()) {
            throw new \RuntimeException('The keys are configured in Neos.OAuth.keys, not kept in files', 1790100014);
        }
        $this->withLock(function () {
            $this->writeNewKeys();
        });
    }

    private function keyContents(string $key): string
    {
        if ($this->keysAreConfigured()) {
            $contents = $this->settings[$key] ?? null;
            if ($contents === null || trim($contents) === '') {
                throw new \RuntimeException(sprintf('Neos.OAuth.keys.%s is not set: configure all three keys, or none to use key files', $key), 1790100015);
            }
            return $contents;
        }
        $this->ensureKeyFiles();
        $contents = file_get_contents($this->settings[$key . 'Path']);
        if ($contents === false) {
            throw new \RuntimeException(sprintf('Could not read the OAuth key "%s"', $this->settings[$key . 'Path']), 1790100012);
        }
        return $contents;
    }

    /**
     * Generates the key files on first use. If only some of them exist, something is wrong: they are not replaced
     */
    private function ensureKeyFiles(): void
    {
        if (!in_array(false, $this->keyFiles(), true)) {
            return;
        }
        $this->withLock(function () {
            $files = $this->keyFiles();
            if (!in_array(false, $files, true)) {
                // generated by a parallel request in the meantime
                return;
            }
            if (in_array(true, $files, true)) {
                throw new \RuntimeException(sprintf(
                    'Some OAuth key files are missing: %s. Restore them, or replace all keys with ./flow oauth:generatekeys --force, which invalidates all issued tokens',
                    implode(', ', array_keys(array_filter($files, static fn (bool $exists) => !$exists))),
                ), 1790100016);
            }
            $this->writeNewKeys();
            $this->logger->info('Generated the OAuth keys', LogEnvironment::fromMethodName(__METHOD__));
        });
    }

    private function writeNewKeys(): void
    {
        $keyPair = openssl_pkey_new(['private_key_bits' => 4096, 'private_key_type' => OPENSSL_KEYTYPE_RSA]);
        if ($keyPair === false || !openssl_pkey_export($keyPair, $privateKey)) {
            throw new \RuntimeException('Could not generate the RSA key pair: ' . openssl_error_string(), 1790100010);
        }
        $details = openssl_pkey_get_details($keyPair);
        if ($details === false) {
            throw new \RuntimeException('Could not extract the public key: ' . openssl_error_string(), 1790100011);
        }
        $this->write($this->settings['privateKeyPath'], $privateKey);
        $this->write($this->settings['publicKeyPath'], $details['key']);
        $this->write($this->settings['encryptionKeyPath'], Key::createNewRandomKey()->saveToAsciiSafeString());
    }

    /**
     * Serializes the generation of keys across processes, so that parallel first requests don't create two key sets
     */
    private function withLock(\Closure $callback): void
    {
        $directory = dirname($this->settings['privateKeyPath']);
        Files::createDirectoryRecursively($directory);
        $lock = fopen($directory . '/.keys.lock', 'c');
        if ($lock === false || !flock($lock, LOCK_EX)) {
            throw new \RuntimeException(sprintf('Could not lock "%s" to generate the OAuth keys', $directory), 1790100017);
        }
        try {
            $callback();
        } finally {
            flock($lock, LOCK_UN);
            fclose($lock);
        }
    }

    /**
     * Writes to a temporary file first, so a key is never read half written
     */
    private function write(string $path, string $contents): void
    {
        Files::createDirectoryRecursively(dirname($path));
        $temporaryPath = $path . '.' . bin2hex(random_bytes(4)) . '.tmp';
        if (file_put_contents($temporaryPath, $contents) === false) {
            throw new \RuntimeException(sprintf('Could not write "%s"', $path), 1790100013);
        }
        // league requires the keys to be readable by the owner only
        chmod($temporaryPath, 0600);
        if (!rename($temporaryPath, $path)) {
            @unlink($temporaryPath);
            throw new \RuntimeException(sprintf('Could not write "%s"', $path), 1790100013);
        }
    }
}
